version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=development
